apiVersion: v1
kind: ConfigMap
metadata:
  name: wetlands-maplibre-config
data:
  config.template.json: |
    {
        "mcp_server_url": "${MCP_SERVER_URL}",
        "llm_model": "minimax-m2",
        "llm_models": [
            {
                "value": "glm-4.7",
                "label": "NRP GLM-4.7",
                "endpoint": "${LLM_ENDPOINT}",
                "api_key": "${PROXY_KEY}"
            },
            {
                "value": "qwen3",
                "label": "NRP Qwen3",
                "endpoint": "${LLM_ENDPOINT}",
                "api_key": "${PROXY_KEY}"
            },
            {
                "value": "gpt-oss",
                "label": "NRP GPT-OSS 120B",
                "endpoint": "${LLM_ENDPOINT}",
                "api_key": "${PROXY_KEY}"
            },
            {
                "value": "kimi",
                "label": "NRP Kimi K2.5",
                "endpoint": "${LLM_ENDPOINT}",
                "api_key": "${PROXY_KEY}"
            },
            {
                "value": "minimax-m2",
                "label": "NRP MiniMax M2.5",
                "endpoint": "${LLM_ENDPOINT}",
                "api_key": "${PROXY_KEY}"
            }
        ]
    }
